# Generated by Django 3.2.4 on 2021-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='sex',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.IntegerField(),
        ),
    ]
