# Generated by Django 3.2.4 on 2021-06-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210625_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='game',
            new_name='user',
        ),
    ]
