# Generated by Django 3.2.4 on 2021-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='movie',
            name='hitFlop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.TextField(default='none'),
        ),
    ]
