# Generated by Django 3.2.4 on 2021-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_movie_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.TextField(default='none'),
        ),
    ]
