# Generated by Django 3.2.4 on 2021-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_movie_imdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(default='none', verbose_name='actors'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(default='none', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hitFlop',
            field=models.IntegerField(default=0, verbose_name='hitFlop'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000, verbose_name='releaseYear'),
        ),
    ]
