# Generated by Django 3.2.4 on 2021-06-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20210626_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
