# Generated by Django 3.2.4 on 2021-06-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
    ]
