# Generated by Django 3.2.4 on 2021-06-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_name_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('singer', models.TextField(default='none', verbose_name='singer')),
                ('genre', models.TextField(default='none', verbose_name='genre')),
                ('album', models.TextField(default='none', verbose_name='album')),
                ('user_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='user_rating')),
            ],
        ),
    ]
