# Generated by Django 3.2.4 on 2021-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.TextField(max_length=10),
        ),
    ]
