# Generated by Django 3.2.4 on 2021-07-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_user_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default='password', max_length=8),
        ),
    ]
