# Generated by Django 3.2.4 on 2021-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_user_details_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
